java.version=17
maven.version=3.9.9
junit.jupiter.version=5.11.4
rest.assured.version=5.5.0
allure.java.version=2.29.1
node.version=22.13.1
npm.version=10.9.2
typescript.version=5.7.3
cypress.version=14.0.1
cucumber.preprocessor.version=22.0.1
allure.cypress.version=3.0.8
appium.version=2.15.0
appium.uiautomator2.driver.version=4.1.0
k6.version=0.56.0
serverest.image=paulogoncalvesbh/serverest:3.2.0
sauce.demo.android.version=2.2.0

