platformName=Android
automationName=UiAutomator2
deviceName=${DEVICE_NAME}
platformVersion=${PLATFORM_VERSION}
udid=${UDID}
app=${APP_PATH}
appPackage=com.saucelabs.mydemoapp.android
appActivity=com.saucelabs.mydemoapp.android.view.activities.SplashActivity
noReset=false
fullReset=false

